### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by stkang** [lincenying/mmf-blog-vue2#1]
[HPM] Proxy created: /api  ->  http://localhost:4000
[HPM] Proxy rewrite rule created: "^/api" ~> "/api"
Listening at http://localhost:8080

webpack built 5cd06c987997142c0870 in 1685ms
Hash: 5cd06c987997142c0870
Version: webpack 2.2.1
Time: 1685ms
    Asset     Size  Chunks  Chunk Names
   app.js  1.08 kB       0  app
 admin.js  1.08 kB       1  admin
vendor.js  1.23 MB       2  vendor

ERROR in ./src/app.js
Module build failed: SyntaxError: C:/Users/stkang90/Desktop/mmf-blog-vue2/src/app.js: Unexpected token (22:4)

  20 |     router,
  21 |     store,
> 22 |     ...App
     |     ^
  23 | })
  24 |
  25 | app.$mount('#app')

 @ multi ./build/dev-client ./src/app.js

ERROR in ./src/admin.js
Module build failed: SyntaxError: C:/Users/stkang90/Desktop/mmf-blog-vue2/src/admin.js: Unexpected token (17:4)

  15 |     router,
  16 |     store,
> 17 |     ...App
     |     ^
  18 | })
  19 |
  20 | app.$mount('#app')

 @ multi ./build/dev-client ./src/admin.js
Child html-webpack-plugin for "admin.html":
         Asset     Size  Chunks  Chunk Names
    admin.html  29.4 kB       0
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  28.4 kB       0
webpack: Failed to compile.

**Comment by lincenying** [comment]
估计是某个依赖升级造成的, 暂时取消使用babel-presets-env
https://github.com/lincenying/mmf-blog-vue2/blob/master/.babelrc

**Comment by lincenying** [comment]
babel-loader 的bug, babel-loader 已经修复
https://github.com/babel/babel-loader/releases
