### ISSUE TITLE
Error: Loading chunk backend-login failed.

### ISSUE THREAD

**Issue by littlejackone** [lincenying/mmf-blog-vue2#14]
访问localhost:8081/backend时，会自动跳转到localhost:8081/，无法进行登录。控制台报错：

<img width="1223" alt="q01" src="https://user-images.githubusercontent.com/8923906/40268502-0b68b8ba-5ba1-11e8-95e2-fbcf1c807eb4.png">
展开第一个错误：
<img width="429" alt="q02" src="https://user-images.githubusercontent.com/8923906/40268515-5f5ae272-5ba1-11e8-8cef-94e0ad528774.png">

**Comment by lincenying** [comment]
connect-history-api-fallback 的一个小问题, 已经修复, 请git pull下

**Comment by littlejackone** [comment]
访问localhost:8081/backend，账户验证通过后，又重新跳转到localhost:8081/backend。登录失败。

**Comment by littlejackone** [comment]
问题解决了，谢谢！
