### ISSUE TITLE
关于进度条

### ISSUE THREAD

**Issue by elva2596** [lincenying/mmf-blog-vue2#2]
博主，你好实在没有看懂你写的进度条怎么就起作用了？？
`    watch: {
        'global.progress'(val) {
            if (val === 0) {
                console.log('0执行了')
                NProgress.set(0)
                NProgress.start()
            } else if (val === 100) {
                console.log('100执行了')
                NProgress.done()
            } else {
                console.log(val)
                NProgress.set(val/100)
                NProgress.start()
            }
        }
    }`
这段代码中间会打印50，这50哪里来的啊？
`router.beforeEach((route, redirect, next) => {
    store.dispatch('global/gProgress', 0)
    next()
})`
路由钩子只在跳转前dispatch一次action,actions再commit mutation ,然后改变state，因为只有这一次发生了state值得改变，最终路由跳转完成了mouted钩子起作用，再次设置100.请问那个中间的state状态的改变如何发生的呢？？？？

**Comment by lincenying** [comment]
https://github.com/lincenying/mmf-blog-vue2/blob/master/src/api/index-client.js#L7
ajax开始请求时, 跳到50%
ajax请求结束后, 跳到100%
如果该页面没有ajax请求, 则有mounted里执行mutations
