### ISSUE TITLE
这里为啥不能用cnpm安装呢？

### ISSUE THREAD

**Issue by bitqiang** [lincenying/mmf-blog-vue2#4]
npm install  #or  yarn
# 注意: 不要用 cnpm 安装依赖

是指不能用淘宝的源安装吗

**Comment by lincenying** [comment]
可以用淘宝的源, 但是不推荐用cnpm安装
你可以用npm或者yarn设置淘宝源.
因为cnpm用的是软链, 有可能会出现丢依赖

**Comment by bitqiang** [comment]
噢噢噢。谢谢了噢。
感觉你好厉害啊。写了那么多。
看得代码都蒙圈，如果想仿照你的实现一次，有什么学习的建议吗

**Comment by lincenying** [comment]
这个代码已经是一个完整的博客源代码, 涉及的依赖比较多,
如果是初学vue的话, 建议先看看官方的入门例子...
如果已经接触过一段时间, 对vue-router和vuex有一点了解再看会比较轻松.
vue-router的官方例子: https://github.com/vuejs/vue-router/tree/dev/examples
vuex的官方例子: https://github.com/vuejs/vuex/tree/dev/examples
