### ISSUE TITLE
系统还缺少一个退出功能

### ISSUE THREAD

**Issue by wwb568109135** [lincenying/mmf-blog-vue2#5]
（1）系统还缺少一个退出功能，若有，就完美了！
（2）前台管理员的在线编辑器，真心插入代码的功能，不好用！

**Comment by lincenying** [comment]
退出功能有想过, 但是没想到按钮放在哪里比较好...所以就搁置了.

markdown的编辑器, 插入代码你应该直接
` ` `javascript
//这里是代码
` ` `
(把` `中间的空格删除)这么写, 可以去搜索下markdown的语法.
